// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6sQiEMzNoFr1nSMwAve3z2timyCTVME8',
    appId: '1:883109663046:web:664c1ec80c8107bce1d547',
    messagingSenderId: '883109663046',
    projectId: 'fir-pro2-b4f83',
    authDomain: 'fir-pro2-b4f83.firebaseapp.com',
    storageBucket: 'fir-pro2-b4f83.appspot.com',
    measurementId: 'G-C2LBEEL65N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKG64n5I47wbnhPSbBzNyZSKtPiZOn7k8',
    appId: '1:883109663046:android:1cbe6a97636f76b1e1d547',
    messagingSenderId: '883109663046',
    projectId: 'fir-pro2-b4f83',
    storageBucket: 'fir-pro2-b4f83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfGHx8vJ5ZL22RAFpaYyRlP6t2Ljfupk',
    appId: '1:883109663046:ios:93c43754d8758e83e1d547',
    messagingSenderId: '883109663046',
    projectId: 'fir-pro2-b4f83',
    storageBucket: 'fir-pro2-b4f83.appspot.com',
    iosBundleId: 'com.example.dbfirebaseproj1Firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfGHx8vJ5ZL22RAFpaYyRlP6t2Ljfupk',
    appId: '1:883109663046:ios:97e9a44fdab8b703e1d547',
    messagingSenderId: '883109663046',
    projectId: 'fir-pro2-b4f83',
    storageBucket: 'fir-pro2-b4f83.appspot.com',
    iosBundleId: 'com.example.dbfirebaseproj1Firestore.RunnerTests',
  );
}
