// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFAUhVLhmZtSiv4mCPyAEMxP_VeCYWiI',
    appId: '1:727811364121:web:3ed931db21527c9c34e188',
    messagingSenderId: '727811364121',
    projectId: 'fir-pro3-5f558',
    authDomain: 'fir-pro3-5f558.firebaseapp.com',
    storageBucket: 'fir-pro3-5f558.appspot.com',
    measurementId: 'G-Y4C6966DDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3cqMxR7CG4p1mmoOQu2pnmw-V-O_e1s',
    appId: '1:727811364121:android:0bad93876b9559b934e188',
    messagingSenderId: '727811364121',
    projectId: 'fir-pro3-5f558',
    storageBucket: 'fir-pro3-5f558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuKWeSxwWmkPx6sZtG8m88987kZeGuE0',
    appId: '1:727811364121:ios:f7f78a9d79ad9bf434e188',
    messagingSenderId: '727811364121',
    projectId: 'fir-pro3-5f558',
    storageBucket: 'fir-pro3-5f558.appspot.com',
    iosBundleId: 'com.example.dbfirebaseproj2Images',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuKWeSxwWmkPx6sZtG8m88987kZeGuE0',
    appId: '1:727811364121:ios:da0cdb6b7ebfeef034e188',
    messagingSenderId: '727811364121',
    projectId: 'fir-pro3-5f558',
    storageBucket: 'fir-pro3-5f558.appspot.com',
    iosBundleId: 'com.example.dbfirebaseproj2Images.RunnerTests',
  );
}
