// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEJQkLwMzHwTU7Wpv1O0Yg4zun7J-bBOU',
    appId: '1:515349484545:web:185ca749c1c2811a111c00',
    messagingSenderId: '515349484545',
    projectId: 'my-book-60735',
    authDomain: 'my-book-60735.firebaseapp.com',
    storageBucket: 'my-book-60735.appspot.com',
    measurementId: 'G-Y65YPZG6XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_LDmLC8uSLmTfXsE6XEQLp3itXWl3AxI',
    appId: '1:515349484545:android:9e8294679ca52345111c00',
    messagingSenderId: '515349484545',
    projectId: 'my-book-60735',
    storageBucket: 'my-book-60735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-aoVg87X8WCxdr--m0449ZERus1iDamY',
    appId: '1:515349484545:ios:adcc554ea3cf6efe111c00',
    messagingSenderId: '515349484545',
    projectId: 'my-book-60735',
    storageBucket: 'my-book-60735.appspot.com',
    androidClientId: '515349484545-n3mifi9i88a8nhqp71lc28c4oahku0on.apps.googleusercontent.com',
    iosClientId: '515349484545-ns1mj4fna1rifb7su34n5md65k97nl7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbfirebaseproj3chatapp',
  );
}
