// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjBvxwb1OiSbFMLUh5Q7tf9bLB4yoLfSo',
    appId: '1:1098223216980:web:53ccc27243dd62161040c1',
    messagingSenderId: '1098223216980',
    projectId: 'blogapp-3bfd3',
    authDomain: 'blogapp-3bfd3.firebaseapp.com',
    storageBucket: 'blogapp-3bfd3.appspot.com',
    measurementId: 'G-KR454WHEME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvDz26aIOGFYoLrn5JZIR1Bubt-ynyuA',
    appId: '1:1098223216980:android:b85ac4bded2852951040c1',
    messagingSenderId: '1098223216980',
    projectId: 'blogapp-3bfd3',
    storageBucket: 'blogapp-3bfd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wJlBg_9H_Hhc96yjZZkSRcnIZGGKRtY',
    appId: '1:1098223216980:ios:2e657a6b46c8f6f21040c1',
    messagingSenderId: '1098223216980',
    projectId: 'blogapp-3bfd3',
    storageBucket: 'blogapp-3bfd3.appspot.com',
    iosBundleId: 'com.example.dbProjBlogappui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wJlBg_9H_Hhc96yjZZkSRcnIZGGKRtY',
    appId: '1:1098223216980:ios:e7a193618dbae1841040c1',
    messagingSenderId: '1098223216980',
    projectId: 'blogapp-3bfd3',
    storageBucket: 'blogapp-3bfd3.appspot.com',
    iosBundleId: 'com.example.dbProjBlogappui.RunnerTests',
  );
}
